sed -i 's/const \[teacherId, setTeacherId\] = useState(classToEdit?.teacher_id || '\''none'\'')/const \[teacherId, setTeacherId\] = useState(classToEdit?.teacher_id || '\''none'\'')\n  const \[programId, setProgramId\] = useState(classToEdit?.program_id || '\''none'\'')/g' src/components/classes/class-dialog.tsx

sed -i 's/fee_per_meeting: parseFloat(feePerMeeting) || 0,/fee_per_meeting: parseFloat(feePerMeeting) || 0,\n      program_id: programId === '\''none'\'' ? null : programId,/g' src/components/classes/class-dialog.tsx

sed -i 's/const { data: teachers, isLoading: isLoadingTeachers } = useTeachers()/const { data: teachers, isLoading: isLoadingTeachers } = useTeachers()\n  const supabase = createClient()\n  const { data: programs, isLoading: isLoadingPrograms } = useQuery({\n    queryKey: ['\''programs'\''],\n    queryFn: async () => {\n      const { data, error } = await supabase.from('\''programs'\'').select('\''* '\'').eq('\''is_active'\'', true)\n      if (error) throw error\n      return data\n    }\n  })/g' src/components/classes/class-dialog.tsx

sed -i '/import { Select, SelectContent/a import { useQuery } from '"'"'@tanstack/react-query'"'"'\nimport { createClient } from '"'"'@/lib/supabase/client'"'"'' src/components/classes/class-dialog.tsx

sed -i '/<Label>Guru Pengajar<\/Label>/i \          <div className="space-y-2">\n            <Label>Program<\/Label>\n            <Select value={programId} onValueChange={setProgramId}>\n              <SelectTrigger>\n                <SelectValue placeholder="Pilih Program" \/>\n              <\/SelectTrigger>\n              <SelectContent>\n                <SelectItem value="none">Belum Ditentukan<\/SelectItem>\n                {!isLoadingPrograms \&\& programs?.map((p: any) => (\n                  <SelectItem key={p.id} value={p.id}>{p.name}<\/SelectItem>\n                ))}\n              <\/SelectContent>\n            <\/Select>\n          <\/div>\n' src/components/classes/class-dialog.tsx
